version: "3.8"
services:
  backend:
    build: ./backend
    env_file: .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"  # tylko localhost (dla Cloudflare Tunnel)
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8000
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"  # tylko localhost (dla Cloudflare Tunnel)